source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SWSegmentedControl_Example' do
  pod 'SWSegmentedControl', :path => '../'

  target 'SWSegmentedControl_Tests' do
    inherit! :search_paths
    
    
    pod 'iOSSnapshotTestCase'
  end
end
