source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SWSegmentedControl_Example', :exclusive => true do
  pod 'SWSegmentedControl', :path => '../'
end

target 'SWSegmentedControl_Tests', :exclusive => true do
  pod 'SWSegmentedControl', :path => '../'

  
end
