source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.3'

use_frameworks!

target 'SWSegmentedControl_Example' do
  pod 'SWSegmentedControl', :path => '../'

  target 'SWSegmentedControl_Tests' do
    inherit! :search_paths
    
    
    pod 'FBSnapshotTestCase'
  end
end
